# Generated by Django 3.2 on 2022-10-12 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpickers',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stock',
            name='area_code_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core_api.areacode'),
        ),
        migrations.AddField(
            model_name='stock',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.organisation'),
        ),
        migrations.AddField(
            model_name='stock',
            name='produce_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core_api.produce'),
        ),
        migrations.AddField(
            model_name='stock',
            name='quantity_suffix_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core_api.producequantitysuffix'),
        ),
        migrations.AddField(
            model_name='stock',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core_api.supplier'),
        ),
        migrations.AddField(
            model_name='stock',
            name='variety_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core_api.producevariety'),
        ),
        migrations.AddField(
            model_name='producevariety',
            name='produce_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core_api.produce'),
        ),
        migrations.AddField(
            model_name='producequantitysuffix',
            name='produce_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core_api.produce'),
        ),
        migrations.AddField(
            model_name='produce',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.organisation'),
        ),
        migrations.AddField(
            model_name='orderstock',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core_api.order'),
        ),
        migrations.AddField(
            model_name='orderstock',
            name='quantity_suffix_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core_api.producequantitysuffix'),
        ),
        migrations.AddField(
            model_name='orderstock',
            name='stock_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core_api.stock'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core_api.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.organisation'),
        ),
        migrations.AddField(
            model_name='customer',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.organisation'),
        ),
        migrations.AddField(
            model_name='areacode',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.organisation'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('category', 'organisation'), name='unique_category_organisation_combination'),
        ),
    ]
