# Generated by Django 3.2.15 on 2022-09-09 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='organisation',
            field=models.ForeignKey(default='000000', on_delete=django.db.models.deletion.CASCADE, to='core_api.organisation'),
            preserve_default=False,
        ),
    ]
