# Generated by Django 3.2 on 2022-10-09 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstock',
            name='invoice_number',
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_number',
            field=models.TextField(default='000000', max_length=20),
        ),
        migrations.AddField(
            model_name='produce',
            name='organisation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core_api.organisation'),
            preserve_default=False,
        ),
    ]
