# Generated by Django 3.2.16 on 2022-10-17 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstock',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.order'),
        ),
        migrations.AlterField(
            model_name='orderstock',
            name='stock_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.stock'),
        ),
        migrations.AddConstraint(
            model_name='produce',
            constraint=models.UniqueConstraint(fields=('name', 'organisation'), name='unique_name_organisation_combination'),
        ),
    ]
