# Generated by Django 3.2.15 on 2022-10-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0003_alter_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='logo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
