# Generated by Django 3.2.16 on 2022-10-17 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0003_auto_20221018_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order items',
            },
        ),
        migrations.CreateModel(
            name='OrderItemStockLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('order_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.orderitem')),
            ],
            options={
                'verbose_name': 'order item stock link',
                'verbose_name_plural': 'order item stock links',
            },
        ),
        migrations.AlterModelOptions(
            name='areacode',
            options={'verbose_name': 'area code', 'verbose_name_plural': 'area codes'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'customer', 'verbose_name_plural': 'customers'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterModelOptions(
            name='organisation',
            options={'verbose_name': 'organisation', 'verbose_name_plural': 'organisations'},
        ),
        migrations.AlterModelOptions(
            name='produce',
            options={'verbose_name': 'produce', 'verbose_name_plural': 'produce'},
        ),
        migrations.AlterModelOptions(
            name='producequantitysuffix',
            options={'verbose_name': 'produce quantity suffix', 'verbose_name_plural': 'produce quantity suffixes'},
        ),
        migrations.AlterModelOptions(
            name='producevariety',
            options={'verbose_name': 'produce variety', 'verbose_name_plural': 'produce varieties'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'stock', 'verbose_name_plural': 'stock'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'supplier', 'verbose_name_plural': 'suppliers'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'team', 'verbose_name_plural': 'teams'},
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_number',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='OrderStock',
        ),
        migrations.AddField(
            model_name='orderitemstocklink',
            name='quantity_suffix_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core_api.producequantitysuffix'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='produce_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core_api.produce'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity_suffix_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core_api.producequantitysuffix'),
        ),
    ]
