# Generated by Django 3.2.15 on 2022-10-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0005_auto_20221018_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='completion_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
