# Generated by Django 3.2.16 on 2022-10-21 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0005_auto_20221018_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='produce_variety_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='core_api.producevariety'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitemstocklink',
            name='stock_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core_api.stock'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='completion_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date_completed',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date_picked',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date_planted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date_seeded',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ehd',
            field=models.DateField(blank=True, null=True),
        ),
    ]
