# Generated by Django 3.2.16 on 2022-10-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0008_alter_stock_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_number',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
