# Generated by Django 3.2.15 on 2022-10-25 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0006_alter_order_completion_date'),
        ('core_api', '0008_alter_stock_options'),
    ]

    operations = [
    ]
