# Generated by Django 3.2 on 2022-10-27 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0009_merge_20221025_1959'),
        ('core_api', '0010_stock_quantity_available'),
    ]

    operations = [
    ]
