# Generated by Django 3.2.15 on 2022-10-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(choices=[(111, 'Organisation Admin'), (100, 'Admin'), (200, 'Team Leader'), (300, 'Office'), (400, 'Worker')], default=400, verbose_name='role'),
        ),
    ]
